// UI primitives barrel (milestone 4.1; design-apply Step 3 adds the hand-off primitives).
export { Button } from './Button'
export { Eyebrow } from './Eyebrow'
export { SectionWrapper } from './SectionWrapper'
export { Input } from './Input'
export { Textarea } from './Textarea'
export { Select } from './Select'
export type { SelectOption } from './Select'
export { StarRating } from './StarRating'
export { VerifiedBadge } from './VerifiedBadge'
export { Skeleton } from './Skeleton'
export { EmptyState } from './EmptyState'
export { Avatar } from './Avatar'
// Hand-off primitives (Step 3) — Card · StatBlock · RankBadge · Badge · Tag:
export { Card } from './Card'
export { StatBlock } from './StatBlock'
export { RankBadge } from './RankBadge'
export { Badge } from './Badge'
export { Tag } from './Tag'
// Superseded but retained until their card-internal consumers migrate (Step 4):
export { PerformanceBadge } from './PerformanceBadge'
export { RisingTalentTag } from './RisingTalentTag'
export { RankIndicator } from './RankIndicator'
export { StatTile } from './StatTile'
